version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - ./ssl_key.key:/ssl_key.key
      - ./combined.crt:/combined.crt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  static:
